# Generated by Django 6.0.3 on 2026-03-26 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('titulo', models.CharField(max_length=20)),
                ('publicacao', models.DateField()),
                ('preco', models.FloatField()),
                ('estoque', models.IntegerField()),
                ('autores', models.ManyToManyField(to='edu.autor')),
                ('editora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.editora')),
            ],
        ),
    ]
